export default {
  alineKaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Aline Santos Barbosa',
    cargo: 'General Director - CEO',
    linkext: 'contatos/ibiama_aline.vcf',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/aline_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
    },
  },
  joelKaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Joel Barbosa',
    cargo: 'Technology and Product - CTO',
    linkext: 'contatos/ibiama_joel.vcf',
    linkedin_url: 'https://www.linkedin.com/in/jafb62',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/joel_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
    },
  },
  cristianeKaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Cristiane Santos Barbosa',
    cargo: 'General Director EU',
    linkext: 'contatos/ibiama_cristiane.vcf',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/cristiane_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
    },
  },


Sarahkaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Sarah Barbosa',
    cargo: 'Design coordinator',
    linkext: 'content/contatos/ibiama_Sarah.vcf',
    linkedin_url : 'https://br.linkedin.com/in/sarah-ramos-de-%C3%A1vila-8b39581a5?',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/sarah_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
     },
  },
  danielKaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Daniel Barbosa',
    cargo: 'Technology and Product',
    linkext: 'contatos/ibiama_daniel.vcf',
    linkedin_url:'https://www.linkedin.com/in/daniel-p-santos-108a338/',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/daniel_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
    },
  },
  lisboaKaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Carlos Lisboa',
    cargo: 'Technology and Product',
    linkext: 'contatos/ibiama_lisboa.vcf',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/lisboa_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
    },
  },
  flaviaKaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Flávia Martins',
    cargo: 'Administrative Management',
    linkext: 'contatos/ibiama_flavia.vcf',
    linkedin_url: 'https://www.linkedin.com/in/nome-de-usuario/',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/flavia_photo.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
    },
  },
    calebekaadi: {
    reflection1: '',
    reflection2: '',
    name: 'Calebe Figueira',
    linkext: 'contatos/ibiama_calebe.vcf',
    cargo:  'Junior Developer',
    input1: '',
    audioreflex1: 'sound/engoma_roupa.mp3',
    videoreflex1: '',
    photo1: 'img/photos/calebe.webp',
    image1: '',
    nextStep: {
      event: 'closeIbi1',
      awardMutation: 'addIbi1ToPercurso',
      goToRouterName: 'reflex:intro',
  },
},
}
